<!DOCTYPE html>
<html>
<head>
    <title>picture</title>
</head>
<body style="background-color:grey;">  
    
       <table border="1" width="500px">
         <tr>
            <td colspan="1">
         
        
<fieldset style="width:5%">
			<legend>PROFILE PICTURE</legend>
			<table width="100px">
				<tr>
                    <td><img src="blank-picture-holder.png" alt="profile pic" style="width:100px;height:100px;"align="Left"></td>
				</tr>
                <tr>
                    <td><input type="file" id="myfile" name="myfile" multiple></td>
                </tr>
                <tr>
                    <td><hr></td>
                </tr>
                <tr>
                <td><input type="submit" name="submit" value="Submit">
				</tr>
			</table>
</fieldset>
</td>
</tr>
</table>
</body>
</html>